name: leakpeak
description: "A privacy and data breach detection app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Added the package for generating launcher icons
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    # It's good practice to create a specific folder for icons
    - assets/icon/
    # Your main logo asset
    - assets/LEAKPEEK-03.png
    # The recaptcha logo for the verification screen
    - assets/recaptcha_logo.png


# Configuration for the launcher icons package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Make sure this path points to your icon file in the assets folder
  image_path: "assets/icon/LEAKPEEK-03.png"